title: LaserSVG
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  LaserSVG is an exension to the SVG file format that allows you 
  to integrate additional information necessary to quickly 
  adapt a design to a different material thickness.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://lasersvg.onrender.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/w/lasersvg-C079"
url: "https://anonymous.4open.science"
#twitter_username: jekyllrb
#github_username:  jekyll

source: ./docs/
theme: minima
markdown: kramdown
#remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/



