source: ./docs/
theme: minima
#remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: LaserSVG
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  LaserSVG is an exension to the SVG file format that allows you 
  to integrate additional information necessary to quickly 
  adapt a design to a different material thickness.
baseurl: "/" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll


